In [1]:
# 2.1 — tạo dữ liệu có seed cố định
import numpy as np

rng = np.random.default_rng(42)   # seed cố định -> mọi người chạy ra cùng một mảng

# TODO: tạo mảng X kích thước (1000, 5) lấy từ phân phối chuẩn.
#       Gợi ý: rng.standard_normal((1000, 5))  — chú ý dấu ngoặc: truyền MỘT tuple
X = rng.standard_normal((1000, 5))

print("shape :", X.shape)
print("ndim  :", X.ndim)
print("dtype :", X.dtype)
print("nbytes:", X.nbytes, "byte  =", X.nbytes / 1024, "KB")
print("Một phần tử chiếm:", X.itemsize, "byte")

shape : (1000, 5)
ndim  : 2
dtype : float64
nbytes: 40000 byte  = 39.0625 KB
Một phần tử chiếm: 8 byte


In [2]:
# 2.2 — tự kiểm tra
assert X.shape == (1000, 5), f"shape sai: {X.shape}"
assert X.ndim == 2, "Phải là mảng 2 chiều"
assert X.dtype == np.float64, f"dtype sai: {X.dtype}"
assert X.nbytes == 1000 * 5 * 8, "nbytes = số phần tử x 8 byte (float64)"

print("2.1 OK — 1000 x 5 x 8 byte =", X.nbytes, "byte")

2.1 OK — 1000 x 5 x 8 byte = 40000 byte


In [3]:
# 2.3 — TRỤC: axis=0 và axis=1 khác nhau chỗ nào
S = np.arange(12).reshape(3, 4)
print(S)
print()

print("S.sum(axis=0) =", S.sum(axis=0), "| shape", S.sum(axis=0).shape,
      "<- gộp CÁC DÒNG lại, còn một số cho mỗi CỘT")
print("S.sum(axis=1) =", S.sum(axis=1), "| shape", S.sum(axis=1).shape,
      "<- gộp CÁC CỘT lại, còn một số cho mỗi DÒNG")

# Cách nhớ: axis=i nghĩa là "trục i BIẾN MẤT khỏi shape".
#           S.shape = (3, 4);  sum(axis=0) -> (4,);  sum(axis=1) -> (3,)

print("S.mean(axis=0) =", S.mean(axis=0))
print("S.max(axis=1)  =", S.max(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

S.sum(axis=0) = [12 15 18 21] | shape (4,) <- gộp CÁC DÒNG lại, còn một số cho mỗi CỘT
S.sum(axis=1) = [ 6 22 38] | shape (3,) <- gộp CÁC CỘT lại, còn một số cho mỗi DÒNG
S.mean(axis=0) = [4. 5. 6. 7.]
S.max(axis=1)  = [ 3  7 11]


In [4]:
# 2.4 — rút gọn theo trục trên X
print("Trung bình từng cột (axis=0):", X.mean(axis=0).round(4))
print("Độ lệch chuẩn từng cột      :", X.std(axis=0).round(4))
print("shape của kết quả           :", X.mean(axis=0).shape, "<- 5 số, một số / cột")

# TODO: in min và max của TOÀN BỘ mảng (gọi .min() / .max() KHÔNG truyền axis),
#       làm tròn 4 chữ số thập phân.
print("Min toàn mảng:", round(X.min(), 4))
print("Max toàn mảng:", round(X.max(), 4))

Trung bình từng cột (axis=0): [-0.0457  0.0092  0.0031 -0.0244 -0.0416]
Độ lệch chuẩn từng cột      : [1.     1.0354 0.9669 1.0183 0.9732]
shape của kết quả           : (5,) <- 5 số, một số / cột
Min toàn mảng: -3.6484
Max toàn mảng: 3.454


In [5]:
# 2.5 — CHUẨN HÓA từng cột bằng BROADCASTING
#
#   X            có shape (1000, 5)
#   X.mean(axis=0) có shape      (5,)
#
# NumPy tự "kéo giãn" mảng (5,) thành (1000, 5) khi trừ — đó là broadcasting.
# Không sao chép dữ liệu, không vòng lặp Python.

# TODO: viết MỘT dòng: lấy X trừ trung bình từng cột rồi chia cho độ lệch chuẩn từng cột
Xs = (X - X.mean(axis=0)) / X.std(axis=0)

print("Trung bình sau chuẩn hóa  :", Xs.mean(axis=0).round(12))
print("Độ lệch chuẩn sau chuẩn hóa:", Xs.std(axis=0).round(12))
print("shape giữ nguyên          :", Xs.shape)

Trung bình sau chuẩn hóa  : [ 0.  0. -0. -0. -0.]
Độ lệch chuẩn sau chuẩn hóa: [1. 1. 1. 1. 1.]
shape giữ nguyên          : (1000, 5)


In [6]:
# 2.6 — tự kiểm tra kết quả chuẩn hóa
assert Xs.shape == X.shape, "Chuẩn hóa không được đổi shape"
assert np.abs(Xs.mean(axis=0)).max() < 1e-9, "Trung bình từng cột phải xấp xỉ 0"
assert np.abs(Xs.std(axis=0) - 1).max() < 1e-9, "Độ lệch chuẩn từng cột phải xấp xỉ 1"

print(f"2.5 OK — sai số trung bình lớn nhất: {np.abs(Xs.mean(axis=0)).max():.2e}")
print(f"         sai số độ lệch chuẩn lớn nhất: {np.abs(Xs.std(axis=0) - 1).max():.2e}")
print("Hai con số trên KHÁC 0 — số dấu phẩy động là thế, nên mới so với 1e-9 chứ không so == 0.")

2.5 OK — sai số trung bình lớn nhất: 2.88e-17
         sai số độ lệch chuẩn lớn nhất: 6.66e-16
Hai con số trên KHÁC 0 — số dấu phẩy động là thế, nên mới so với 1e-9 chứ không so == 0.


In [7]:
    # 2.7 — hai cách làm cùng một việc
import time

def chuan_hoa_vong_lap(A):
    '''Chuẩn hóa từng cột bằng vòng lặp Python thuần — cách CHẬM.'''
    n_dong, n_cot = A.shape
    out = np.empty_like(A)
    for j in range(n_cot):
        cot = [A[i, j] for i in range(n_dong)]
        tb = sum(cot) / n_dong
        do_lech = (sum((v - tb) ** 2 for v in cot) / n_dong) ** 0.5
        for i in range(n_dong):
            out[i, j] = (A[i, j] - tb) / do_lech
    return out


def chuan_hoa_vector(A):
    '''Chuẩn hóa từng cột bằng broadcasting — cách NHANH.'''
    # TODO: một dòng return, giống hệt ô 2.5
    return (A - A.mean(axis=0)) / A.std(axis=0)


print("Đã định nghĩa 2 hàm.")

Đã định nghĩa 2 hàm.


In [8]:
# 2.8 — ĐO THỜI GIAN bằng time.perf_counter
#
# Dùng perf_counter chứ không dùng %timeit: perf_counter là Python thuần,
# chạy được cả trong notebook lẫn trong file .py chạy bằng dòng lệnh.

t0 = time.perf_counter()
X_loop = chuan_hoa_vong_lap(X)
t_loop = time.perf_counter() - t0

# Bản vector hóa chạy quá nhanh để đo chính xác trong 1 lần
# -> chạy N_LAP lần rồi lấy trung bình.
N_LAP = 100
t0 = time.perf_counter()
for _ in range(N_LAP):
    X_vec = chuan_hoa_vector(X)
t_vec = (time.perf_counter() - t0) / N_LAP

print(f"Vòng lặp Python  : {t_loop * 1000:9.3f} ms")
print(f"Vector hóa NumPy : {t_vec  * 1000:9.4f} ms  (trung bình {N_LAP} lần chạy)")
print(f"Nhanh hơn        : {t_loop / t_vec:9.1f} lần")


Vòng lặp Python  :     4.165 ms
Vector hóa NumPy :    0.0924 ms  (trung bình 100 lần chạy)
Nhanh hơn        :      45.1 lần


In [9]:
# 2.9 — tự kiểm tra: nhanh hơn thì được, nhưng phải RA CÙNG KẾT QUẢ
assert np.allclose(X_loop, X_vec), "Hai cách phải cho cùng một kết quả"
assert np.allclose(X_vec, Xs), "...và phải khớp với Xs tính ở ô 2.5"

speedup = t_loop / t_vec
assert speedup > 5, f"Chỉ nhanh hơn {speedup:.1f} lần — kiểm tra lại chuan_hoa_vector"

print(f"2.7 OK — hai cách cho cùng kết quả, vector hóa nhanh hơn {speedup:.0f} lần.")
print("Nhanh mà sai thì vô dụng: luôn kiểm tra kết quả trước, đo tốc độ sau.")

2.7 OK — hai cách cho cùng kết quả, vector hóa nhanh hơn 45 lần.
Nhanh mà sai thì vô dụng: luôn kiểm tra kết quả trước, đo tốc độ sau.
